name: CD

on:
  workflow_call:
    secrets:
      SERVER_HOST:
        required: true
      SERVER_USERNAME:
        required: true
      SERVER_DEPLOY_KEY:
        required: true
      SERVER_DESTINATION:
        required: true
jobs:
  Deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Download repository
        uses: actions/checkout@v3

      - name: Install docker compose
        uses: KengoTODA/actions-setup-docker-compose@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - run: docker compose version

      - name: Download lint script
        run: |
          curl -o "lint.sh" "https://raw.githubusercontent.com/United-Earth-Team/.github/main/docker-compose/lint.sh"
          chmod +x ./lint.sh

      - name: Run lint
        run: |
          ./lint.sh

      - name: Upload files to server
        uses: AEnterprise/rsync-deploy@v1.0.2
        env:
          DEPLOY_KEY: ${{ secrets.SERVER_DEPLOY_KEY }}
          ARGS: -avz --delete
          SERVER_PORT: 22
          FOLDER: "./"  # folder which used to push. The path is relative to the root directory of the repository.
          SERVER_IP: ${{ secrets.SERVER_HOST }} # reference configuration, server host name (IP or domain name)
          USERNAME: ${{ secrets.SERVER_USERNAME }} # reference configuration, login username for server
          SERVER_DESTINATION: ${{ secrets.SERVER_DESTINATION }} # Deploy to the target folder

      - name: Deploy
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SERVER_DEPLOY_KEY }}
          port: 22
          script: |
            cd ${{ secrets.SERVER_DESTINATION }}
            ./deploy.sh
